name: "Build and deploy storybook"
on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, closed, synchronize]
  push:
    branches:
      - "main"

jobs:
  storybook-preview:
    runs-on: ubuntu-latest
    name: Deploy storybook
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
        if: github.event.action != 'closed'
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-v??-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-v1-
        if: github.event.action != 'closed'
      - name: Install dependencies checking cache hit
        run: yarn install --immutable
        if: github.event.action != 'closed'

      # This is how you'll use the action
      - name: build -> deploy storybook
        uses: Sauloxd/review-apps@v2.0.0
        with:
          branch: "gh-pages"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          apps: |
            {
              "storybook": {
                "build": "yarn build-storybook",
                "dist": "storybook-static"
              }
            }
